package com.example.xverifydemoapp.utils

enum class ChannelCallback {
    ON_ERROR_MESSAGE,
    ON_FINISH_MRZ,
    ON_SCAN_QR_CODE_SUCCESS,
    ON_START_SESSION_NFC,
    ON_FINISH_NFC,
    ON_VERIFYING_EID_WITH_RAR,
    ON_VERIFY_EID_SUCCESS,
    ON_STEP_LIVENESS,
    ON_PLAY_SOUND,
    ON_LIVENESS_SUCCESS,
    ON_VERIFYING_FACE_LIVENESS,
    ON_VERIFY_FACE_LIVENESS_FINISH,
    //OCR
    ON_VERIFY_OCR_SUCCESS,
    //Bio
    ON_RESULT_CHECK_ONBOARDING_STATUS,
    ON_BIO_VERIFY_OTP_SUCCESS,
    ON_BIO_VERIFY_FACE_MATCHING_SUCCESS,
    //EKYB
    ON_RESULT_SCAN_DOCUMENT
}