package com.example.xverifydemoapp.utils

enum class FlutterChannelConstant {
    DECODE_MRZ_BY_PATH,
    VERIFY_EID_METHOD,
    GET_CARD_TYPE,
    CANCEL_SESSION_NFC,
    VERIFY_EKYC_METHOD,
    VERIFY_OCR_METHOD,

    //Common
    SEND_BUSINESS_TYPE,
    SEND_DEVICE_ID,
    SEND_ENV_METHOD,
    //OCR
    REQUEST_VERIFY_OCR,

    //Bio-2345
    REQUEST_CHECK_ONBOARDING_STATE,
    REQUEST_VERIFY_FACE_BIOMETRIC,
    REQUEST_BIO_VERIFY_OTP,
    REQUEST_GET_DATA_ONBOARD_SUCCESS,
    REQUEST_BIO_VERIFY_FACE_TRANSFER,
    REQUEST_GET_DATA_TRANSFER_SUCCESS,

    //Ekyb
    REQUEST_SCAN_EKYB,
    VERIFY_TAX_CODE_ADVANCE
}