package com.example.xverifydemoapp.extentions

import vn.jth.xverifysdk.network.models.response.VerifyOCRResponseModel


fun VerifyOCRResponseModel.toMap(): Map<String,Any> {
    return mapOf(
        "transactionCode" to transactionCode,
        "fullName" to fullName,
        "surName" to surName,
        "givenName" to givenName,
        "personNumber" to personNumber,
        "passportNumber" to passportNumber,
        "dateOfExpiry" to dateOfExpiry,
        "gender" to gender,
        "placeOfOrigin" to placeOfOrigin,
        "placeOfResidence" to placeOfResidence,
        "issuedAt" to issuedAt,
        "dateOfIssue" to dateOfIssue,
        "nationality" to nationality,
        "dateOfBirth" to dateOfBirth,
        "frontType" to frontType,
        "frontValid" to frontValid,
        "backType" to backType,
        "backValid" to backValid,
        "identificationSign" to identificationSign,
        "personNumberConfidence" to personNumberConfidence,
        "fullNameConfidence" to fullNameConfidence,
        "dateOfBirthConfidence" to dateOfBirthConfidence,
        "genderConfidence" to genderConfidence,
        "nationalityConfidence" to nationalityConfidence,
        "placeOfOriginConfidence" to placeOfOriginConfidence,
        "placeOfResidenceConfidence" to placeOfResidenceConfidence,
        "dateOfExpiryConfidence" to dateOfExpiryConfidence,
        "identificationSignConfidence" to identificationSignConfidence,
        "dateOfIssueConfidence" to dateOfIssueConfidence,
        "addressDistrict" to addressDistrict,
        "addressTown" to addressTown,
        "addressWard" to addressWard,
        "hometownDistrict" to hometownDistrict,
        "hometownTown" to hometownTown,
        "hometownWard" to hometownWard,
        "addressDistrictDigitCode" to addressDistrictDigitCode,
        "addressTownDigitCode" to addressTownDigitCode,
        "addressWardDigitCode" to addressWardDigitCode,
        "hometownDistrictDigitCode" to hometownDistrictDigitCode,
        "hometownTownDigitCode" to hometownTownDigitCode,
        "hometownWardDigitCode" to hometownWardDigitCode,
        "addressDistrictAreaCode" to addressDistrictAreaCode,
        "addressTownAreaCode" to addressTownAreaCode,
        "addressWardAreaCode" to addressWardAreaCode,
        "hometownDistrictAreaCode" to hometownDistrictAreaCode,
        "hometownTownAreaCode" to hometownTownAreaCode,
        "hometownWardAreaCode" to hometownWardAreaCode,
        "frontInvalidCode" to frontInvalidCode,
        "backInvalidCode" to backInvalidCode,
        "frontInvalidMessage" to frontInvalidMessage,
        "backInvalidMessage" to backInvalidMessage,
    )

}
